Adding pictures and blog post
dig-eg-gaz/blog-posts pull request #7
Opened 2016-10-08 18:43 UTC by CelitaS

2016-10-08 18:44 UTC, CelitaS commented
Adding blog post 1

2016-10-10 14:30 UTC, whanley requested changes
Good piece, Celita. I wonder if you could tell us a bit more about the content of the invention for natives article (an example?) and/or give a summary about the death of the princess? What society did she seem to be a part of?

2016-10-10 14:30 UTC, whanley commented on 2016-10-08-Egyptian-Gazette-Views-on-Imperialism.md
> +Gazette, it is very interesting the attitude toward this imperialism varies widely throughout the
remove "it is very interesting"

2016-10-10 14:30 UTC, whanley commented on 2016-10-08-Egyptian-Gazette-Views-on-Imperialism.md
> +sentence-long description of an invent important to African natives. This follows with the
invention?

2016-10-10 14:30 UTC, whanley commented on 2016-10-08-Egyptian-Gazette-Views-on-Imperialism.md
> +  thumb: "Khedivial-Princess.png"
Choose just one image for the header and thumb.

2016-10-29 22:25 UTC, merged